.comment\
**************************************************************
*
*              Keypad scanning routine
*
*    Derived from the 'Phoenix MIDI Computer' pmon.mac, 1987
*
*    By RCL9
*	(Rob's Retro Computing Archive)
*	RetroComputingArchive@gmail.com
*	https://github.com/rcl9
*
**************************************************************\

#include	"keytbls.h"		; Keypad special key equates

auxconfig	equ	0eh		; config. port on auxiliary board
aux$image	db 	00		; memory image of auxiliary config port

pa$data	equ	010h			; PIO port a data register

extrn		keyt1			; Unshifted keys table
extrn		keyt2			; Down shifted keys table
extrn		keyt3			; Up shifted keys table

; ----------------------------------------------------------------------

keypad$in:	call	scan$keypad	; Wait for a character
		jr	z,keypad$in
		push	af		; save the character
kypdwait:	call	scan$keypad	; wait to release the key
		jr	nz,kypdwait
		pop	af
		ret			; A = character from keypad

; Scan the keypad ( A = 0 if no character)

scan$keypad:	push	bc
		push	de
		push	hl

; first check for shift_up key

		ld	hl,keyt1	; unshifted keypad
		ld	a,(aux$image)
		or	7
		out	(auxconfig),a	; look at column 7
		nop
		nop
		nop
		in	a,(pa$data)	; get row info
		bit	1,a		; shift down?
		jr	z,sdown		; yes, do shift down
		bit	2,a		; shift up pressed?
		jr	nz,scan2		; no, try rest of keyboard

; shift up pressed

		ld	hl,keyt3	; shift up keypad
		jr	scan2

; shift down pressed

sdown:		ld	hl,keyt2	; shift down keypad

scan2:		push	hl		; save the keypad table address
		ld	b,0		; start at left column
scan1:		ld	a,(aux$image)	; pick up auliary port image
		and	0f8h		; kill lower 3 bits
		or	b		; put in the column bits
		out	(auxconfig),a
		in	a,(pa$data)	; get row bits
		and	7		; get row
		bit	0,a		; 0 --> Enter row?
		jr	nz,try2nd	; no, try next row
		ld	a,b
		jr	lookupkey

try2nd:		bit	1,a		; 5 --> Shift_down row?
		jr	nz,try3rd	; no, try next row
		ld	a,b
		add	a,8
		jr	lookupkey

try3rd:		bit	2,a		; F1 --> Shift_up row?
		jr	nz,trynext
		ld	a,b
		add	a,16
		jr	lookupkey

trynext:	ld	a,b		; get column number
		inc	a		; go to next one
		ld	b,a		; get registers ready
		cp	8		; at last row?
		jr	nz,scan1	; no, keep going
		jr	nokeypress	; no key found.

lookupkey:	pop	hl		; get keyboard table address
		push	hl
		ld	e,a
		ld	d,0
		add	hl,de
		ld	a,(hl)		; get the key
		cp	0		; a shift key?
		jr	z,nokeypress	; yes, it doesn't count as a keypress!

; debounce the key

		push	af		; save the character
		ld	hl,200h
debounce:	dec	hl		; wait a while
		ld	a,h
		or	l
		jr	nz,debounce
		pop	af		; get back the character

		jr	keyrtn		; return with proper status

; no keypressed, return NULL (0) key

nokeypress:	xor	a		; return no keyress status

keyrtn:		pop	hl		; kill the keyboard table address
		pop	hl
		pop	de
		pop	bc
		or	a		; set status (zero = no character)
		ret
